name: offline_sync_manager_example
description: "Demonstrates how to use the offline_sync_manager plugin."
publish_to: 'none'

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  offline_sync_manager:
    path: ../


  cupertino_icons: ^1.0.8

  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
